### ISSUE TITLE
Variable not in scope:htf_xxx_thisModulesTests :: TestSuite from Test.Framework

### ISSUE THREAD

**Issue by andrewufrank** [digital-asset/ghcide#667]
I use the [`Test.Framework`] (https://hackage.haskell.org/package/test-framework-0.8.2.0/docs/Test-Framework.html). Test.Framework uses a precompiler to produce code, called with `{-# OPTIONS_GHC -F -pgmF htfpp #-}`.
ghcide complains that the variable produced by the precompiler are not seen. How can I handle this in the `yaml` file?

**Comment by pepeiborra** [comment]
Sounds like a ghcide bug. Can you provide a minimal example that displays the issue?

**Comment by andrewufrank** [comment]
will come in a couple of hours.

**Comment by andrewufrank** [comment]
i have put an example in https://github.com/andrewufrank/minimalForTest/tree/ghcide_testFramework. 
now the problem is not the same, but ghcide cannot find the test-framework package. I assume once this is overcome, the previously mentioned error is reappearing. 

if you have questions - i should be around the next few days.

**Comment by pepeiborra** [comment]
I'm happy to take a look once you have an example that reproduces the issue

**Comment by andrewufrank** [comment]
Run `stack test`. Runs - tests fail, as expected. 
But `ghcide` fails, it cannot find `Test.Framework` which is either in package `test-framework` or `HTF`. `HTF` is in the dependencies for tests.  I assume there is a confusion between the two modules with the same name in two different packages. 

It is not the error I saw before but it is a bug where `stack test` runs (which I take that there is no problem in my code, which may be wrong) and `ghcide` does not run. 

Thank you for your efforts! I hope ghcide will be a success; Haskell needs an IDE which works and is stable.

**Comment by pepeiborra** [comment]
Your example project is lacking a `hie.yaml` file. Please add one and see if it reproduces the bug.

**Comment by andrewufrank** [comment]
Now I see the error: the produced cabal file includes an `other-modules' with `Path_SimpleTest` which is (theoretically necessary). gen-hie produces with this a main 

```
cradle:
  stack:
    - path: "././."
      component: "TestSimple:lib"

    - path: "./src/ClassMain.hs"
      component: "TestSimple:exe:foo"

    - path: "./src/Paths_TestSimple.hs"
      component: "TestSimple:exe:foo"

    - path: "./tests"
      component: "TestSimple:test:test1"
```

If i delete the unnecessary entry for `TestSimple:exe:foo` the problem goes away. Is this a bug in `implicit-hie`?

**Comment by andrewufrank** [comment]
In my real project I have now a similar error:

Following your advice, I have produced a hie.yaml (which included all sort of executables for packages imported but not interesting). Running ghcide produces a number of errors, but if I start ghcide from VScode, it fails with the error

````
Message: 
  Could not load module ‘Distribution.Simple’
  It is a member of the hidden package ‘Cabal-3.0.1.0’.
  You can run ‘:set -package Cabal’ to expose it.
  (Note: this unloads all the modules in the current scope.)
````

The hie.yaml (after edits) is: 

````
cradle:
  stack:
    - path: "./."
      component: "uniform-json:lib"

    - path: "./tests"
      component: "uniform-json:test:jsontest"

    - path: "../uniform-algebras/."
      component: "uniform-algebras:lib"

    - path: "../uniform-cmdLineArgs/."
      component: "uniform-cmdLineArgs:lib"

    
    - path: "../uniform-convenience/."
      component: "uniform-convenience:lib"

    
    - path: "../uniform-error/."
      component: "uniform-error:lib"

    
    - path: "../uniform-fileio/."
      component: "uniform-fileio:lib"

   
    - path: "../uniform-strings/."
      component: "uniform-strings:lib"

   
    - path: "../uniform-time/."
      component: "uniform-time:lib"
````
The original hie.yaml was 

````
frank@santafe:~/Workspace8/uniform/uniform-json$ gen-hie
cradle:
  stack:
    - path: "./."
      component: "uniform-json:lib"

    - path: "./tests"
      component: "uniform-json:test:jsontest"

    - path: "../uniform-algebras/."
      component: "uniform-algebras:lib"

    - path: "../uniform-cmdLineArgs/."
      component: "uniform-cmdLineArgs:lib"

    - path: "../uniform-cmdLineArgs/src/CmdLineArgsExample.hs"
      component: "uniform-cmdLineArgs:exe:cmdLineExample"

    - path: "../uniform-cmdLineArgs/src/--.hs"
      component: "uniform-cmdLineArgs:exe:cmdLineExample"

    - path: "../uniform-cmdLineArgs/src/other-modules:.hs"
      component: "uniform-cmdLineArgs:exe:cmdLineExample"

    - path: "../uniform-cmdLineArgs/src/Main2sub.hs"
      component: "uniform-cmdLineArgs:exe:cmdLineExample"

    - path: "../uniform-cmdLineArgs/tests"
      component: "uniform-cmdLineArgs:test:errortest"

    - path: "../uniform-convenience/."
      component: "uniform-convenience:lib"

    - path: "../uniform-convenience/tests"
      component: "uniform-convenience:test:TestHarnessTestAuto"

    - path: "../uniform-error/."
      component: "uniform-error:lib"

    - path: "../uniform-error/tests"
      component: "uniform-error:test:errortest"

    - path: "../uniform-fileio/."
      component: "uniform-fileio:lib"

    - path: "../uniform-fileio/tests"
      component: "uniform-fileio:test:fileioTestAuto"

    - path: "../uniform-strings/."
      component: "uniform-strings:lib"

    - path: "../uniform-strings/tests"
      component: "uniform-strings:test:stringTestAuto"

    - path: "../uniform-time/."
      component: "uniform-time:lib"

    - path: "../uniform-time/tests"
      component: "uniform-time:test:timetest"
````
I hope this is a related problem (otherwise I would have had to open a new issue).
